# Universal Medical Residency Scheduler - Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler-app
  namespace: medical-scheduler
  labels:
    app: scheduler-app
    version: "1.0.0"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: scheduler-app
  template:
    metadata:
      labels:
        app: scheduler-app
        version: "1.0.0"
    spec:
      containers:
      - name: scheduler-app
        image: universal-medical-scheduler:latest
        ports:
        - containerPort: 8000
          name: http
        - containerPort: 9090
          name: metrics
        env:
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: scheduler-config
              key: ENVIRONMENT
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: scheduler-config
              key: LOG_LEVEL
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: scheduler-secrets
              key: SECRET_KEY
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: scheduler-secrets
              key: DATABASE_URL
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: scheduler-secrets
              key: REDIS_URL
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: app-logs
          mountPath: /app/logs
        - name: app-uploads
          mountPath: /app/uploads
      volumes:
      - name: app-logs
        persistentVolumeClaim:
          claimName: scheduler-logs-pvc
      - name: app-uploads
        persistentVolumeClaim:
          claimName: scheduler-uploads-pvc
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: scheduler-service
  namespace: medical-scheduler
  labels:
    app: scheduler-app
spec:
  selector:
    app: scheduler-app
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP
  type: ClusterIP